### PR TITLE
KASM-3972 use an array of known scaling values to produce pixel perfect output

### PR DESCRIPTION
**Pull request by thelamer**
This syncs up with the scaling options available in Windows: 

settings

As far as automating actual UI scaling for XFCE this exec will do that: 
```
xfsettingsd --replace --daemon && xfconf-query -v -c xsettings -p /Gdk/WindowScalingFactor -s 2
```

Unfortunately xfce for window scaling only supports 1x or 2x, to facilitate a scaling change like this to automate it we would need the ability to send this to kasmvnc upstream.

### CODE REVIEW

**Review by mmcclaskey — CHANGES_REQUESTED** [review]
While this works with desired affects on screens that have, what I will call medium DPI, it does not work well for devices that have a high DPI. What I suggest is having a threshold based on the window.devicePixelRatio. For devicePixelRatios below 2, do what you have. 

For device pixel ratios at 2 or above, the logic will be different for a whole number versus a fractional number. For 2 or any whole number, do nothing, which is the current logic. This works well for MacBooks which have a pixel ration of 2. With it being an even number, anti-aliasing is not needed and it looks sharp.

For non-even numbers, higher than 2, that is tricky and we likely couldn't be sure unless we had a device that actually had this ratio. I feel like the best thing to do would be to adjust things such that an effective pixel ratio of 2 is used.

Giving the user the control to change this logic could be useful, but here is a screenshot of KasmVNC using the logic on this branch, with a pixel ratio of 2:1. It is not very clear in the screenshot, but look at the URL bar up top and how large it is compared to the Kasm session. It is not really useable, but I know there are some freaks out there that prefer to work in the native resolution.


image

**Comment by thelamer** [comment]
As discussed this has been modified to only fire on 1.25 and 1.5x scaling ratios as those are common default scaling ratios for default windows installations on any screen over 1920x1080.

**Comment by thelamer** [comment]
@mmcclaskey I modified the pixel perfect logic to be a checkbox and accept parent messages. 
The logic is only triggered if that flag is set and will override any other scaling outside of ultra low video quality modes.
This gives the user the option to flag it on if needed.
Let me know if this works for you and we can get this tick box in kasmweb.

**Comment by mmcclaskey** [comment]
@thelamer, vnc.html is missing the corresponding control and that causes an exception in ui.js when connecting. Please see enable_webrtc for an example. Please rename toggle_hdpi to enable_hdpi so that it matches the vernacular used in other controls.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/5209269/220912383-42dd67a5-8c0c-46cd-a80f-7622b8e88922.png"

**Comment by thelamer** [comment]
@mmcclaskey my fault forgot to commit vnc.html, I modified the setting name as recommended. Let me know if you see anything else.

**Review by mmcclaskey — APPROVED** [review]

**Pull request merged**
